# Generated by Django 4.1.7 on 2023-03-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email_address', models.CharField(max_length=250)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.account')),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('listing_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=250)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.account')),
            ],
        ),
    ]
