# Generated by Django 4.1.7 on 2023-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
