# Generated by Django 4.1.7 on 2023-04-02 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_listing_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('etsy_store_id', models.CharField(max_length=250)),
                ('store_name', models.CharField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='userstore',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user'),
        ),
        migrations.AddField(
            model_name='listing',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.store'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='userstore',
            constraint=models.UniqueConstraint(fields=('store_id', 'user_id'), name='unique_store_user'),
        ),
    ]
