# Generated by Django 4.1.7 on 2023-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_store_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Test Title', max_length=250),
            preserve_default=False,
        ),
    ]
